backend/controllers/SiteController.php
<?php
    namespace backend\controllers;

    use common\models\Settings;
    use common\models\Settings\System;
    use common\utilities\Language;
    use Yii;
    use common\forms\Login as LoginForm;
    use common\models\User;

    class SiteController extends BaseController{

        public function beforeAction($action)
        {
            if($action->id === "save-grid-view-settings"){
                $this->enableCsrfValidation = false;
            }

            return parent::beforeAction($action);
        }

        public function actionIndex()
        {
            $this->view->registerJsFile("/scripts/stats.js");

            return $this->render('index', [
                'users' => User::find()->where(['status' => User::STATUS_ACTIVE])->all(),
            ]);
        }

        public function actionLogin()
        {
            $this->layout = "auth";

            if (!Yii::$app->user->isGuest) {
                return $this->goHome();
            }

            $model = new LoginForm();
            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                return $this->redirect(['index']);
            }
            return $this->render('login', [
                'model' => $model,
            ]);
        }

        public function actionLogout()
        {
            Yii::$app->user->logout();

            $session = Yii::$app->session;
            $session->remove("adminAccess");

            return $this->goHome();
        }

        public function actionChangeLang($symbol)
        {
            if(Settings::getOne('language_level', System::MODULE) === "cookie"){
                $language = new Language();
                $language->setCookieLanguage($symbol);
            }

            return $this->goBack();
        }
    }

backend/controllers/UserController.php
<?php
    namespace backend\controllers;

    use backend\models\GridViewConfig;
    use Yii;
    use common\models\User;
    use yii\helpers\ArrayHelper;
    use yii\web\NotFoundHttpException;
    use yii\web\Response;
    use yii\widgets\ActiveForm;
    use backend\models\UserCreate;
    use backend\models\UserUpdate;
    use backend\searches\User as UserSearch;

    class UserController extends BaseController{

        public function actionIndex()
        {
            $searchModel = new UserSearch();
            $gridViewColumns = GridViewConfig::prepareData("common\\models\\User");
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->render('index', [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
                'gridViewColumns' => $gridViewColumns
            ]);
        }
        public function actionView($id)
        {
            if(Yii::$app->user->can("view self user") || Yii::$app->user->can("view users")){
                $model = $this->findModel($id);

                if(Yii::$app->user->can("view self user") && $model->id != Yii::$app->user->getId()){
                    return $this->redirectWithMessage(['index'],
                        Yii::t("system", "You are not allowed to view this object."), "warning");
                }

                return $this->render('view', [
                    'model' => $model,
                ]);
            }
        }
        public function actionCreate()
        {
            if(Yii::$app->user->can("create user")){
                $model = new UserCreate();
                $roles = Yii::$app->authManager->getRoles();
                $roles = ArrayHelper::map($roles, 'name', 'description');
                $avatars = User::getAvatars();

                if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
                    Yii::$app->response->format = Response::FORMAT_JSON;

                    return ActiveForm::validate($model);
                }

                if ($model->load(Yii::$app->request->post()) && $model->create()) {
                    return $this->redirectWithMessage(['view', 'id' => $model->user->id],
                        Yii::t("user", "Object was created successfully."));
                }
                else {
                    return $this->render('create', [
                        'model' => $model,
                        'roles' => $roles,
                        'avatars' => $avatars,
                    ]);
                }
            }
            else{
                return $this->redirectWithMessage(['index'],
                    Yii::t("user", "You are not allowed to create new user."), "warning");
            }
        }
        public function actionUpdate($id)
        {
            $user = Yii::$app->user;

            if($user->can('update users') || $user->can('update self user')){
                $model = new UserUpdate($id);
                $roles = Yii::$app->authManager->getRoles();
                $roles = ArrayHelper::map($roles, 'name', 'description');
                $avatars = User::getAvatars();

                if($user->can('update self user') && $model->id != $user->getId()){
                    return $this->redirectWithMessage(['index'],
                        Yii::t("system", "You are not allowed to edit this object."), "warning");
                }

                if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
                    Yii::$app->response->format = Response::FORMAT_JSON;

                    return ActiveForm::validate($model);
                }

                if ($model->load(Yii::$app->request->post()) && $model->save()) {
                    return $this->redirectWithMessage(['view', 'id' => $model->id],
                        Yii::t("system", "Object was updated successfully."));
                }
                else {
                    return $this->render('update', [
                        'model' => $model,
                        'roles' => $roles,
                        'avatars' => $avatars,
                    ]);
                }
            }
            else{
                return $this->redirectWithMessage(['index'],
                    Yii::t("system", "You are not allowed to edit this object."), "warning");
            }
        }
        public function actionDelete($id)
        {
            $user = Yii::$app->user;

            if($user->can("delete users") || $user->can("delete self user")){
                $model = $this->findModel($id);

                if($model->deletable === 1){
                    $userString = $model->username . "(" . $model->name . ")";

                    if($user->can("delete self user") && $model->id != $user->getId()){
                        return $this->redirectWithMessage(['index'],
                            Yii::t("system", "You are not allowed to delete this object."), "warning");
                    }

                    if($model->delete()){
                        if(Yii::$app->user->identity->getId() == $model->id){
                            Yii::$app->user->logout();
                        }

                        return $this->redirectWithMessage(['index'],
                            Yii::t("user", "Account {account} was successfully deleted.", ['account' => $userString]));
                    }
                }
                else{
                    return $this->redirectWithMessage(['index'],
                        Yii::t("system", "This object cannot be deleted."), "warning");
                }
            }
        }
        protected function findModel($id){
            if (($model = User::findOne($id)) !== null) {
                return $model;
            }
            else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
        }
    }

backend/views/partials/footer.php
<?php
    use common\models\Settings;
    use common\models\Settings\System;

/** @var Settings $footerText */
$footerText = Settings::getOne('footer_text', System::MODULE, false);
?>

<footer class="main-footer">
    <span><?= ($footerText->value) ? $footerText->value : $footerText->default; ?></span>
</footer>

backend/views/partials/header.php
<?php
    use common\models\Language;
    use common\models\Settings;
    use common\models\Settings\System;
    use yii\helpers\Url;

    $user = Yii::$app->user->identity;
    $languages = Language::prepareForForm("backend");
?>

<header class="main-header">

    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle hidden-lg hidden-md" data-toggle="offcanvas" role="button">
            <span class="sr-only"><?= Yii::t("system", "Toggle navigation"); ?></span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?= $user->avatar; ?>" class="user-image" alt="User Image">
                        <span class="hidden-xs">
                            <?= $user->username;?>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated-dropdown-menu">
                        <li class="user-header">
                            <img src="<?= $user->avatar; ?>" class="img-circle" alt="User Image">
                            <p>
                                <?= $user->username; ?>
                                <small><?= Yii::t("system", "Joined"); ?> <?= $user->created_at; ?></small>
                            </p>
                        </li>

                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="<?= Url::toRoute(["user/view", 'id' => Yii::$app->user->identity->id]); ?>" class="btn btn-default btn-flat"><?= Yii::t("system", "Account"); ?></a>
                            </div>
                            <div class="pull-right">
                                <a href="<?= Url::toRoute("/logout"); ?>" class="btn btn-default btn-flat"><?= Yii::t("system", "Logout"); ?></a>
                            </div>
                        </li>
                    </ul>
                </li>
                <?php if(Settings::getOne('language_level', System::MODULE) === "cookie"): ?>
                    <li class="dropdown lang lang-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-language"></i>
                        </a>
                        <ul class="dropdown-menu animated-dropdown-menu list">
                            <?php foreach($languages AS $symbol => $language):?>
                                <li><a href="<?= Url::toRoute(['site/change-lang', 'symbol' => $symbol]);?>"><?= $language; ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                <?php endif; ?>
                <li>
                    <a href="<?= Yii::getAlias("@frontendLink");?>">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
            </ul>
        </div>

    </nav>
</header>

backend/views/partials/loadScreen.php
<div class="loadScreen">
    <i class="fa fa-circle-o-notch fa-spin loadIcon"></i>
</div>

backend/views/partials/sidebar.php
<?php
    use yii\helpers\Url;
    $user = Yii::$app->user->identity;
?>
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <a href="<?= Url::toRoute(["user/view", 'id' => Yii::$app->user->identity->id]); ?>">
                    <img src="<?= $user->avatar;?>" class="img-circle" alt="User Image">
                </a>
            </div>
            <div class="pull-left info">
                    <p>
                        <a href="<?= Url::toRoute(["user/view", 'id' => Yii::$app->user->identity->id]); ?>">
                            <?= $user->username;?>
                        </a>
                    </p>
                    <a href="mailto:<?= $user->email;?>">
                        <i class="fa fa-envelope text-success"></i>
                        <?= $user->email; ?>
                    </a>
            </div>
        </div>
        
        <?php if(isset($this->params['sidebarMenu'])): ?>
            <?= $this->params['sidebarMenu']->render(); ?>
        <?php endif; ?>
    </section>
</aside>